### ISSUE TITLE
Cannot open the big file

### ISSUE THREAD

**Issue by yuefei7746** [sindresorhus/quick-look-plugins#102]
When I want to preview a TXT format file of about 22MB, it takes about 10 seconds to load, and it opens quickly with the original tool.

**Comment by sindresorhus** [comment]
This is not the place to ask support questions for the plugins.

**Comment by jeffbyrnes** [comment]
@yuefei7746 to clarify, you’ll want to go to the repo for the particular plugin that you think is slowing things down & ask there; this repo is simply provided as a convenience to install all of these plugins, no development of them occurs here.

**Comment by yuefei7746** [comment]
well, I'm sorry
