### ISSUE TITLE
Many QL generators fail on Catalina

### ISSUE THREAD

**Issue by waylonis** [sindresorhus/quick-look-plugins#112]
It looks like the increased security on Catalina requires additional signing or notarization.

**Comment by sindresorhus** [comment]
You’ll have to open an issue on the repos of the affected plugins, not here. This is just a list.

**Comment by shkm** [comment]
List or not, does anyone have a solution for this?

**Comment by gino8080** [comment]
nothing new? any quicklook plugin is blocked

**Comment by jeffbyrnes** [comment]
You will want to look into each of the QuickLook plugins individual repositories to see if they have rebuilt their plugin to be notarized. If so, you’ll be able to install the newer version & use them.

**Comment by skywinder** [comment]
@sindresorhus please, specify in the list the supported verion to not confuse the users. 
Can confirm, that `qlstephen` and `qlmarkdow` doesn't work on 10.15.1

**Comment by skywinder** [comment]
related comment with list of compatability: https://github.com/sindresorhus/quick-look-plugins/issues/115#issuecomment-546612663
