### ISSUE TITLE
Drawio Quick-look plugin

### ISSUE THREAD

**Issue by norbertbede** [sindresorhus/quick-look-plugins#122]
I would be happy to collaborate on draw.io quicklook extension.
Draw.io is a diagram tool - very affordable for modern html documentation and multi-platforming.

**i have created issue for drawio community well.**
https://github.com/jgraph/drawio/issues/1026

**xref to api**
https://github.com/jgraph/drawio-github
https://github.com/jgraph/drawio-integration

thanks, norbert

**Comment by sindresorhus** [comment]
This is just a list of extensions. I didn't actually make them.
