### ISSUE TITLE
Wishlist: Display waveform or spectrogram for audio files

### ISSUE THREAD

**Issue by ghost** [sindresorhus/quick-look-plugins#13]
Found somebody else who also wants it: http://www.simonecoen.com/2012/03/04/idea-for-quick-look-audio-plugin/
And another: https://apple.stackexchange.com/questions/22926/lightweight-audio-waveform-viewer

**Comment by Haroenv** [comment]
Could be made using either [peak.js](http://www.bbc.co.uk/rd/blog/2013/10/audio-waveforms) or [waveform.js](https://github.com/katspaugh/wavesurfer.js), but I'm not knowledgeable enough for that.

**Comment by sindresorhus** [comment]
https://github.com/seagirl/QLWaveForm

**Comment by prohtex** [comment]
Oh man I would love to be able to see a spec of a flac from the QuickLook preview window. I wonder how much work it would be.

**Comment by AlexPoulsen** [comment]
looks like @ideoforms made one in 2018 but didn't release it https://blog.chirp.io/chirp-christmas-hackathon-2018/

**Comment by ideoforms** [comment]
@AlexPoulsen It needs a bit of polish, but perfect is the enemy of done, etc... I’ll put the code on GitHub shortly and that should be the encouragement I need to develop it further ;-) Thanks for the nudge!

**Comment by prohtex** [comment]
> @AlexPoulsen It needs a bit of polish, but perfect is the enemy of done, etc... I’ll put the code on GitHub shortly and that should be the encouragement I need to develop it further ;-) Thanks for the nudge!
Incredible! Can't wait to try it!

**Comment by ideoforms** [comment]
Update: I have been looking into releasing my QuickLook spectrogram plugin code. However, it seems that since Catalina, macOS does not let QuickLook plugins override the Finder previews for default system file types (including `public.audio`). This means that the spectrogram preview wouldn't work for the vast majority of audio files (wav, aif, mp3, etc).

If anyone knows a way to work around this, I would be keen to hear it as I would really like to make this available. Suggestions welcomed! @prohtex @AlexPoulsen

**Comment by ChesterYue** [comment]
> Update: I have been looking into releasing my QuickLook spectrogram plugin code. However, it seems that since Catalina, macOS does not let QuickLook plugins override the Finder previews for default system file types (including `public.audio`). This means that the spectrogram preview wouldn't work for the vast majority of audio files (wav, aif, mp3, etc).
> 
> 
> 
> If anyone knows a way to work around this, I would be keen to hear it as I would really like to make this available. Suggestions welcomed! @prohtex @AlexPoulsen 

[Same as public.image](https://github.com/Nyx0uf/qlImageSize/issues/45#issuecomment-610852166)

**Comment by ideoforms** [comment]
Exactly @ChesterYue - I think your diagnosis is right, but it means that Apple may be intentionally withdrawing this functionality. Let me know if you find any alternative approaches in the appex extension  system that could help.

**Comment by prohtex** [comment]
> Update: I have been looking into releasing my QuickLook spectrogram plugin code. However, it seems that since Catalina, macOS does not let QuickLook plugins override the Finder previews for default system file types (including `public.audio`). This means that the spectrogram preview wouldn't work for the vast majority of audio files (wav, aif, mp3, etc).
> 
> If anyone knows a way to work around this, I would be keen to hear it as I would really like to make this available. Suggestions welcomed! @prohtex @AlexPoulsen

My primary interest is flac, which should work, right?

**Comment by ideoforms** [comment]
@prohtex Sadly, the plugin uses ExtAudioFile to read the audio data, which doesn't support flac files. This means that the list of audio formats it supports is exactly the same as the list that Apple classes as a system file type -- which, it seems, can't be overridden at present in terms of their QuickLook previews. 

I've pushed the code to GitHub in case anyone wants to have a play:
https://github.com/ideoforms/qlspectrogram

**Comment by prohtex** [comment]
> @prohtex Sadly, the plugin uses ExtAudioFile to read the audio data, which doesn't support flac files. This means that the list of audio formats it supports is exactly the same as the list that Apple classes as a system file type -- which, it seems, can't be overridden at present in terms of their QuickLook previews.
> 
> I've pushed the code to GitHub in case anyone wants to have a play:
> https://github.com/ideoforms/qlspectrogram
I built this on 10.13 and it is working perfectly for FLAC files. I'd LOVE to figure out a way to get it running on Catalina for FLAC.
Thanks SO much for this!!!

**Comment by AlexPoulsen** [comment]
I haven't upgraded to catalina yet, since I'm sure a lot of the audio plugins I use won't work and I haven't yet had the motivation to create a second partition and try plugins in that to see what works and what doesn't, so the code as-is should work for me for the foreseeable future
