### ISSUE TITLE
"Suspicious Package" Homebrew Cask needs clarification

### ISSUE THREAD

**Issue by simshanith** [sindresorhus/quick-look-plugins#15]
Slightly tongue-in-cheek, but mostly serious here - it should be clear that the `suspicious-package` cask is for checking out suspicious packages with quick look, and is not a suspicious package itself. Definitely did a double-take when seeing that package name in a long list of other casks.

Thanks for providing such a great resource!

**Comment by jrodl3r** [comment]
seeing this flash across your screen at 8am (before your first sip of coffee) is... funny.

```
==> Verifying checksum for Cask suspicious-package
==> Installing Cask suspicious-package
```

**Comment by Jahhein** [comment]
I guess I should chime in not to worry about the domain name the application is under which is `com.mothersruin.SuspiciousPackage` if you see it.
