### ISSUE TITLE
cert-quicklook and provisionql

### ISSUE THREAD

**Issue by AlJohri** [sindresorhus/quick-look-plugins#25]
consider adding:
```
brew cask install cert-quicklook provisionql
```

https://code.google.com/p/cert-quicklook/
https://github.com/ealeksandrov/ProvisionQL

I have tested ```cert-quicklook``` myself and it works well.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/quick-look-plugins#other
https://github.com/sindresorhus/quick-look-plugins#provisionql

**Comment by AlJohri** [comment]
wow, sorry about that!
