### ISSUE TITLE
Break text selection

### ISSUE THREAD

**Issue by ManUtopiK** [sindresorhus/quick-look-plugins#26]
It's possible to make text selectable in Quick Look previews.
Just need to enable a hidden Finder setting:
`defaults write com.apple.finder QLEnableTextSelection -bool TRUE; killall Finder`

But quick-look-plugins break this possibility...

Tested with OS X 10.9 and 10.10.

**Comment by jjarava** [comment]
What plugin did you test/where do you see it broken?

I've got the setting enabled and I've tested that I can copy text from 2 different file types:

An .md file:
![ql plugins broken-2015-02-01_11-20-01](https://cloud.githubusercontent.com/assets/2682444/5991763/8b72df4c-aa04-11e4-81df-767db9d2fcac.jpg)

A .taskpaper file <sup>1</sup> (text-like):
![taskpaper-ql-2015-02-01_11-23-18](https://cloud.githubusercontent.com/assets/2682444/5991774/520b993c-aa05-11e4-9962-3fc859eeb168.jpg)

And a text file:
![txt-ql-2015-02-01_11-26-56](https://cloud.githubusercontent.com/assets/2682444/5991780/b7503dd4-aa05-11e4-9364-dc4341ed76eb.jpg)

and in all cases I've been able to copy text and paste it somewhere else... 

<sup>1</sup> Sorry for the blurring, but I didn't have the time to generate a .taskpaper file that was completely "*publishable*" online, so I've opted for cropping and masking the parts that are not completely public :smile:

**Comment by arthurvr** [comment]
@ManUtopiK See above comment. What plugin did you tested this with?

**Comment by sindresorhus** [comment]
Text selection works fine for me too with all the plugins installed, on latest OS X.

**Comment by ManUtopiK** [comment]
Sorry, I missed my mention in this issue.

I updated all plugins and tested again. Selection now works, but I can't copy text with `command-c`. Keyboard doesn't work, but I can copy from menu Edit !?

I deactivated all quicklook plugin, and tested one by one.
It's seem QLColorCode cause this trouble.

Hope this can help you.

**Comment by sindresorhus** [comment]
Open an issue on the QLColorCode issue tracker ;)
