### ISSUE TITLE
wishlist: gif

### ISSUE THREAD

**Issue by ldong** [sindresorhus/quick-look-plugins#28]
I know there is a GIF plugin at [source forge](http://sourceforge.net/projects/animgifqlgen/).

But it doesn't appear to be working on **Yosemite**, so I *wish* somebody could port it.

**Comment by sindresorhus** [comment]
Animated gifs are supported on OS X Quick Look without a plugin. Works fine for me on Yosemite. You might have an issue with your system.

**Comment by ldong** [comment]
Yep, after I removed it, it worked.

```bash
cd ~/Library/QuickLook
rm AnimatedGIF_QL.README.rtf
rm AnimatedGIF_QL.qlgenerator
qlmanage -r
```
