### ISSUE TITLE
whishlist: svg images

### ISSUE THREAD

**Issue by alesrosina** [sindresorhus/quick-look-plugins#30]
I'm using this software for svg images - i think i would make sense to include it on the list.

http://gapplin.wolfrosch.com/

**Comment by sindresorhus** [comment]
Ask them to put the Quick Look plugin on Homebrew.

Though I don't really see the point as at least OS X Yosemite supports SVG natively:

```sh
❯ qlmanage -m | grep svg
  public.svg-image -> /System/Library/QuickLook/Web.qlgenerator (675.42 - loaded)
```

**Comment by mrh-is** [comment]
OS X _does_ support it natively, but the Gapplin plugin is better. OS X
puts a ton of unnecessary whitespace around the SVG, whereas Gapplin trims
that and makes the content much easier to see.

**Comment by sindresorhus** [comment]
> Ask them to put the Quick Look plugin on Homebrew.

Alright, happy to add it when the above is done ;)

**Comment by kevva** [comment]
Does it really support it natively? I've tried on two different Macbooks with the same result (a white window).

**Comment by sindresorhus** [comment]
@kevva I disabled all my Quick Look plugins (none which were susceptible for that functionality anyways) and `qlmanage -r && qlmanage -r cache` to reset everything. Still showed multiple different SVG images just fine.

**Comment by kevva** [comment]
Lol, weird. Might been something wrong with the image.

**Comment by Martin-Pitt** [comment]
If the content is a white SVG, it will show as a white window. It's just the native QL plugin being just that rubbish.

**Comment by mkstix6** [comment]
Sorry, I know this is old and closed but perhaps someone found a solution; won't be offended if you ignore me.

Ye, do any of you know how to stop QuickLook showing small SVG icons like this, with a massive white area, preferably zoomed in more so the icon is bigger?

![Screenshot 2020-04-24 at 18 27 54](https://user-images.githubusercontent.com/1573136/80240258-74528d80-8659-11ea-9aa9-6476727d054b.png)

This file has a 24px view-box:

```
<svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="m0 0h24v24 etc…</svg>
```
