### ISSUE TITLE
Text selection doesn't work on OS X 10.11

### ISSUE THREAD

**Issue by gaoryrt** [sindresorhus/quick-look-plugins#34]
Run this in your terminal to allow text selection in the Quick Look window:

`defaults write com.apple.finder QLEnableTextSelection -bool true && killall Finder`

cannot support OS X El Capitan

**Comment by sindresorhus** [comment]
Apple changed how it works in 10.11. Nothing I can do anything about. Also see: https://github.com/mathiasbynens/dotfiles/issues/580.

**Comment by gaoryrt** [comment]
okay   
thx for reply
