### ISSUE TITLE
Suspicious-package does not install through homebrew on El Capitan.

### ISSUE THREAD

**Issue by jaredpatton173** [sindresorhus/quick-look-plugins#38]
System Version:	OS X 10.11.1 (15B42)
Kernel Version:	Darwin 15.0.0

Jareds-MBP:~ jared$ brew cask install suspicious-package
==> Satisfying dependencies
==> Installing Formula dependencies from Homebrew
unar ... already installed
complete
==> Downloading http://www.mothersruin.com/software/downloads/SuspiciousPackage.
Already downloaded: /Library/Caches/Homebrew/suspicious-package-latest.xip
Error: Command failed to execute!

==> Failed command:
["#<Pathname:/usr/local/bin/unar>", "-q", "-D", "-o", "/var/folders/95/97_nt5_d2vgdsbl8xlw7sfv40000gn/T/d20151121-1222-ca9ng6", "--", "#<Pathname:/Library/Caches/Homebrew/suspicious-package-latest.xip>"]

==> Output of failed command:
/Library/Caches/Homebrew/suspicious-package-latest.xip: 

==> Exit status of failed command:
#<Process::Status: pid 1258 SIGSEGV (signal 11)>
Jareds-MBP:~ jared$

**Comment by razasyedh** [comment]
Already reported upstream: caskroom/homebrew-cask#15025

**Comment by adidalal** [comment]
(I'm one of the maintainers of Homebrew Cask)

Ran across this open issue and just wanted to let you know it's been resolved upstream:

```
[~] > brew cask install suspicious-package
==> Satisfying dependencies
==> Installing Formula dependencies from Homebrew
unar ... already installed
complete
==> Downloading http://www.mothersruin.com/software/downloads/SuspiciousPackage.
######################################################################## 100.0%
==> No checksum defined for Cask suspicious-package, skipping verification
==> Symlinking QuickLook Plugin 'Suspicious Package.qlgenerator' to '/Users/adit
🍺  suspicious-package staged at '/opt/homebrew-cask/Caskroom/suspicious-package/latest' (55 files, 712K)
```

**Comment by sindresorhus** [comment]
@adidalal Thanks for the update :)
