### ISSUE TITLE
Error while downloading with Homebrew (JSON issue?)

### ISSUE THREAD

**Issue by MarkLalor** [sindresorhus/quick-look-plugins#39]
Seems like a simple issue, but I'm not that familiar with homebrew. Is there just a problem with the quicklook-json plugin? Or is it my machine?

Error: Uh oh, could not identify primary container for '/Library/Caches/Homebrew/quicklook-json-latest.zip'

**Comment by sindresorhus** [comment]
This is not the place to get Hombrew support.
