### ISSUE TITLE
Installing QLStephen destroys Quick Look for other registered types in El Capitan

### ISSUE THREAD

**Issue by joehanna** [sindresorhus/quick-look-plugins#42]
Once this plugin has been installed to view files without a file extension, Quick Look no longer works for files such as PDF, PNG, GIF, etc.

They are all pretty much considered text files and Quick Look displays them as such.
![screen shot 2016-03-01 at 9 40 11 pm](https://cloud.githubusercontent.com/assets/1687108/13424660/4023d6da-dff6-11e5-8c4a-fd795c6b6e04.png)

**Comment by sindresorhus** [comment]
Why are you opening this here? → https://github.com/whomwah/qlstephen/issues

**Comment by joehanna** [comment]
Sorry to bother you. I followed a link which brought me here. I checked to see if you forked the repo so I could indeed go back to the original author and it didn't say "Forked from..."
