### ISSUE TITLE
[DOCUMENTATION] HowTo instal `boost` dependency

### ISSUE THREAD

**Issue by jousch** [sindresorhus/quick-look-plugins#44]
http://www.pyimagesearch.com/2015/04/27/installing-boost-and-boost-python-on-osx-with-homebrew/

**Comment by sindresorhus** [comment]
❓

**Comment by jousch** [comment]
The problem is, that when you try to install all the casks and you don't have installed boost (a dependency of highlight), the build of boost don't finish. I have installed the ql plugins after I installed python and boost with other options:
```
brew install python
brew install boost --with-python
brew install boost-python
brew install cask qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql qlimagesize webpquicklook suspicious-package
```

I thought it would help others, if you mention this as note in the readme of this repo.

cheers

**Comment by sindresorhus** [comment]
What exactly requires boost and boost-python? `python` comes with OS X.

**Comment by jousch** [comment]
When I run the last mentioned command, `highlight` is a dependency of any of the casks. Highlight depends on boost. Homebrew can't brew boost without the `--with-python` option. I Also had to install python with brew, because the "brewing" didn't worked with the OSX-python "version".

**Comment by sindresorhus** [comment]
That sounds like a bug in that cask. Casks are supposed to define dependencies they need and brew will install them for you. I would recommend you track down which cask it is that causes it and open an issue on https://github.com/caskroom/homebrew-cask/issues ;)
