### ISSUE TITLE
Suspicious Package

### ISSUE THREAD

**Issue by briatte** [sindresorhus/quick-look-plugins#49]
… has moved to http://www.mothersruin.com/software/SuspiciousPackage/get.html

It's now both an app and a QL generator. Moving the generator on its own to `~/Library/QuickLook` won't work (at least on OS X 10.9 Mavericks), although the app works fine otherwise.

**Comment by sindresorhus** [comment]
Should still work fine. See: https://github.com/caskroom/homebrew-cask/issues/19813

**Comment by briatte** [comment]
`brew cask install suspicious-package` did not work for me, hence my issue.

**Comment by sindresorhus** [comment]
@briatte Then open an issue on Homebrew Cask. This is just a list of Quick Look plugins.

**Comment by briatte** [comment]
Will do.
