### ISSUE TITLE
Brew cask installation not working.

### ISSUE THREAD

**Issue by lukasoppermann** [sindresorhus/quick-look-plugins#57]
Hey,

so I tried installing this on OSX 10.11.6, it says it worked, if I try reinstalling it, it says it is already installed, however the files are not within `/Library/QuickLook` and so it does not work.

However copying files manually into the folder works. But I would much rather install via casks, as it would allow for automatic updates. 

Can you give me any tips how I can get it working? What information do you need?

**Comment by sindresorhus** [comment]
This is not really the place to ask Homebrew Cask support questions.

https://github.com/caskroom/homebrew-cask/issues
