### ISSUE TITLE
QLMarkdown didn't work normally in MacOS Sierra 10.12

### ISSUE THREAD

**Issue by johnwatsondev** [sindresorhus/quick-look-plugins#59]
There are some SNAPSHOTS:

![hello md](https://cloud.githubusercontent.com/assets/12760754/19677157/8e1bd358-9aca-11e6-95b6-2fdeced08196.jpg)
![hello markdown](https://cloud.githubusercontent.com/assets/12760754/19677163/9215ba46-9aca-11e6-81d2-938f2738d3a5.jpg)

My test file's content is simple with "### Hello". 
Did I miss some important details? 
Thanks for any advice.

**Comment by hawkrives** [comment]
@johnwatsondev Please open your issue on the [QLMarkdown repository](https://github.com/toland/qlmarkdown). This is merely a list of plugins, and we cannot provide support here.

**Comment by johnwatsondev** [comment]
@hawkrives Sorry. I got it. Thanks again.
