### ISSUE TITLE
Consider adding QuickLookAPK to the More section

### ISSUE THREAD

**Issue by ngyikp** [sindresorhus/quick-look-plugins#60]
Could be useful for Android developers/power users, still works good on 10.12.1

https://github.com/hezi/QuickLookAPK

<img width="1048" alt="screen shot 2016-11-19 at 4 16 33 pm" src="https://cloud.githubusercontent.com/assets/6135313/20454194/3c299b3a-ae74-11e6-8c4b-bd124e5dcd67.png">

**Comment by sindresorhus** [comment]
Sure. Do a pull request ;)
