### ISSUE TITLE
No seperate plugin for webp needed anymore, qlImageSize already supports it 

### ISSUE THREAD

**Issue by therealmarv** [sindresorhus/quick-look-plugins#63]
After installing only

https://github.com/Nyx0uf/qlImageSize#installation

I was able to preview/view webp images already. The extra webp plugin is not needed anymore IMHO.

Thanks for your recommendation list! :)

**Comment by grrowl** [comment]
Can confirm, on a fresh installation of Mojave I can quick look .webp files with `qlimagesize` without `webpquicklook` installed through brew

**Comment by sindresorhus** [comment]
We can remove it from the default install command and add a note about it to the `qlimagesize` entry, but I still think it's useful to have it for people that don't want `qlimagesize`.
