### ISSUE TITLE
Consider adding QuickLookAddict

### ISSUE THREAD

**Issue by tattali** [sindresorhus/quick-look-plugins#68]
Could be useful for read subtitles.

https://github.com/tattali/QLAddict
![QuickLookAddict](https://cloud.githubusercontent.com/assets/10502887/24485802/f2676c62-1506-11e7-8d4c-0973ac2dba03.png)

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I don't think that's something developers specifically needs.
