### ISSUE TITLE
something wrong with the icon

### ISSUE THREAD

**Issue by leoxu1007** [sindresorhus/quick-look-plugins#69]
After I installed zip preview, I found something with the icon is wrong.
![screen shot 0029-05-07 at 11 12 38](https://cloud.githubusercontent.com/assets/22413258/25777671/bc6b846c-3316-11e7-87dd-cf093bdb73c5.png)

**Comment by sindresorhus** [comment]
Open an issue on the Quick Plugin plugin in question. This is just a list of plugins. I didn't make them.

**Comment by leoxu1007** [comment]
sorry, but where can I find the "quick plugin plugin" webpage?

**Comment by hawkrives** [comment]
There are links to all the plugins in the README.
