### ISSUE TITLE
Txt file, Chinese garbled.

### ISSUE THREAD

**Issue by zoushunqiang** [sindresorhus/quick-look-plugins#71]
Install the quick-look before, form the windows txt file Chinese display is normal, after installation shows garbled. Use a text editor without this problem.
<img width="315" alt="1" src="https://cloud.githubusercontent.com/assets/17295434/25836878/03782b74-34bd-11e7-889a-14bb81e1b2ca.png">
<img width="319" alt="2" src="https://cloud.githubusercontent.com/assets/17295434/25836880/044a64b8-34bd-11e7-879a-21123d77dfd5.png">

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/quick-look-plugins/issues/69#issuecomment-299688815
