### ISSUE TITLE
Txt file Chinese garbled

### ISSUE THREAD

**Issue by zoushunqiang** [sindresorhus/quick-look-plugins#72]
Install the quick-look before, form the windows txt file Chinese display is normal, after installation shows garbled. 
Use a text editor to open it  without this problem.
<img width="319" alt="2" src="https://cloud.githubusercontent.com/assets/17295434/25837895/a4f15d86-34c2-11e7-8fb2-38bfd8673b03.png">

**Comment by sindresorhus** [comment]
Please stop opening issues.
