### ISSUE TITLE
BetterZipQL does not show icons for folders or files

### ISSUE THREAD

**Issue by Suavatore** [sindresorhus/quick-look-plugins#75]
<img width="1018" alt="screen shot 2017-10-10 at 8 50 24 am" src="https://user-images.githubusercontent.com/13889273/31373002-9eeb7896-ad98-11e7-82e5-d3cee90a79a7.png">

**Comment by sindresorhus** [comment]
This is not the place to report issues for the Quick Look plugins.

**Comment by Suavatore** [comment]
I know. Just wanted to let you know that the plugin was deprecated and probably shouldn't be displayed amongst those that aren't.
