### ISSUE TITLE
After installing all, preview missing in Finder column layout

### ISSUE THREAD

**Issue by NimaiMalle** [sindresorhus/quick-look-plugins#76]
macOS High Sierra 10.13.1 (17B48)

I noticed that XML files were previewing but JSON files were not, in the right-most column of Finder windows, in column view mode.  I searched and found this repo, and installed all using the brew cask method in the readme.
Now, when I use the spacebar to quick view, I can see XML and JSON content just fine, but in the Finder window itself, in the right-most column, I only get the piece of paper with curled corner image, for JSON and XML.  (Oddly, the piece of paper is narrower for JSON files...)

**Comment by sindresorhus** [comment]
This is just a list of Quick Look plugin. You need to open the issue on the relevant plugin.
