### ISSUE TITLE
need a plugin for a quick look of a folder

### ISSUE THREAD

**Issue by hanzichi** [sindresorhus/quick-look-plugins#83]
need a plugin for a quick look of a folder, to list the files inside, what's your opinion?

**Comment by jrobichaud** [comment]
It only is a list of existing quick look plugins. If it exists already I guess you can submit the plugin to be added to the list, otherwise close your issue.

**Comment by hanzichi** [comment]
@jrobichaud  sorry, I mistook that the maintainer was the developer for the plugins

**Comment by ayanmw** [comment]
With Command+Down Command+Up ,or Command + Left ,Command+Right  ,you do not need a plugin to see folder's files, cause you just see them .

**Comment by hanzichi** [comment]
@ayanmw I don't really understand you
