### ISSUE TITLE
update quicklook plugins dir

### ISSUE THREAD

**Issue by ryanaltair** [sindresorhus/quick-look-plugins#86]
there is no ` ~/Library/QuickLook` anymore since macOS 10.13,
so for manually install:
rather than

> Move the downloaded .qlgenerator file to ~/Library/QuickLook

it should be

> Move the downloaded .qlgenerator file to /Library/QuickLook

**Comment by esaruoho** [comment]
I'm running macOS High Sierra 10.13.4 and I do have a `~/Library/Quicklook` for sure.

**Comment by ryanaltair** [comment]
add some pic to prove that
<img width="352" alt="2018-04-05 22 08 30" src="https://user-images.githubusercontent.com/2869522/38370994-00dbb960-391e-11e8-9770-10a8280e7a32.png">
<img width="267" alt="2018-04-05 22 08 43" src="https://user-images.githubusercontent.com/2869522/38370998-0291b8e0-391e-11e8-987e-1da54f5a96f5.png">

**Comment by hawkrives** [comment]
You just need to create the ~/Library/QuickLook folder yourself, I think. The system will still check it for QuickLook generators.

**Comment by ryanaltair** [comment]
Thanks hawkrives, will check it later. For now put plugins into /Library/QuickLook works already. Guess that put plugins to /Library/QuickLook will works for all user and ~/Library/QuickLook will only work for current user. Someone have a check?

**Comment by hawkrives** [comment]
That is how macOS uses those two folders, yes. Same with ~/Library/Fonts et. all.

**Comment by ryanaltair** [comment]
ye both works
