### ISSUE TITLE
Problems getting it to work

### ISSUE THREAD

**Issue by efueng** [sindresorhus/quick-look-plugins#97]
I think I'm missing a step somewhere as I can't get these to work after installing.

I'm on macOS 10.14.3 and used the individual brew cask commands. I restarted the Quick Look manager. I also restarted the machine. I tried installing from my admin account as well as my non-admin account. Any help is appreciated, as these look like AWESOME extensions!

**Comment by schroef** [comment]
I believe some need to go in the user folder. DId you check that?

**Comment by efueng** [comment]
Where in the user folder?

On Jan 27, 2019, at 12:05 PM, schroef <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe some need to go in the user folder. DId you check that?

**Comment by schroef** [comment]
The user folder can be quick acces by useing ~ so in this case its; ~/Library/QuickLook
By the way if you type the first letter it will autofill. This way you can cycle over folder. Its kind of slow though.

PS which ones do not work?

**Comment by schroef** [comment]
PS i also remember some use some parts of the same code. Therefor they interfere with other and stop those from working. Some are a bit clunky as well, they slow down the system a lot.

**Comment by efueng** [comment]
Ok thank you. I had to create a QuickLook folder in my user/Library. Previously I had it in the system wide library folder

On Jan 27, 2019, at 12:16 PM, schroef <notifications@github.com<mailto:notifications@github.com>> wrote:


PS i also remember some use some parts of the same code. Therefor they interfere with other and stop those from working. Some are a bit clunky as well, they slow down the system a lot.

**Comment by schroef** [comment]
Im not sure which ones dont work. I dont use all of these, but i have most of them in the main quicklook folder. I only have a dropbox-, blender- and sketchup-quicklook plugin in my user folder
